'use client';

import { AppLink } from './app-link';
import { FormEvent, useEffect, useMemo, useState } from 'react';
import { AppHeader } from './app-header';
import { useSession } from '../lib/session';
import { api, json } from '../lib/api';

type Document = { id: string; document_no?: string; document_type?: string; issue_date?: string; party_name?: string; status?: string; total_paise?: number; upload_name?: string | null; source?: string };
type Ref = { id: string; name?: string; code?: string; vehicle_no?: string };
type Overview = { suppliers: Ref[]; buyers: Ref[]; items: Ref[]; saudas: Ref[]; gate: Ref[] };
type Draft = { type: string; party: string; item_id: string; sauda_id: string; gate_entry_id: string; description: string; quantity: string; unit: string; rate: string; gst_rate: string; tax_mode: string; issue_date: string; notes: string };
const money = (paise: number | undefined) => paise == null ? 'Restricted' : new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(paise / 100);
const today = () => new Date().toISOString().slice(0, 10);
const emptyDraft = (): Draft => ({ type: 'SALES_INVOICE', party: '', item_id: '', sauda_id: '', gate_entry_id: '', description: '', quantity: '', unit: 'KG', rate: '', gst_rate: '5', tax_mode: 'INTRA', issue_date: today(), notes: '' });

export function DocumentsApp() {
  const { session, sessionError } = useSession();
  const [documents, setDocuments] = useState<Document[]>([]);
  const [overview, setOverview] = useState<Overview | null>(null);
  const [query, setQuery] = useState('');
  const [error, setError] = useState<string | null>(null);
  const [upload, setUpload] = useState<File | null>(null); const [uploadType, setUploadType] = useState('PAYMENT_RECEIPT');
  const [draft, setDraft] = useState<Draft>(emptyDraft); const [saving, setSaving] = useState(false);
  const load = async () => { const [docs, refs] = await Promise.all([api<{ documents: Document[] }>('/api/documents'), api<Overview>('/api/overview')]); setDocuments(docs.documents); setOverview(refs); };
  useEffect(() => { if (session) void load().catch((cause: unknown) => setError(cause instanceof Error ? cause.message : 'Could not load documents')); }, [session]);
  async function uploadFile(event: FormEvent) { event.preventDefault(); if (!upload) return setError('Choose a file to upload.'); if (upload.size > 1024 * 1024) return setError('Uploads are limited to 1 MB.'); const data = new FormData(); data.set('file', upload); data.set('document_type', uploadType); try { setError(null); await api('/api/documents/upload', { method: 'POST', body: data }); setUpload(null); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not upload document'); } }
  async function createDocument(event: FormEvent) {
    event.preventDefault(); const quantity = Number(draft.quantity); const ratePaise = Math.round(Number(draft.rate) * 100); const [partyKind, partyId] = draft.party.split(':');
    if (!draft.description.trim() || !Number.isFinite(quantity) || quantity < 0 || !Number.isFinite(ratePaise) || ratePaise < 0) { setError('Enter a description, non-negative quantity, and valid rate.'); return; }
    setSaving(true); setError(null);
    try {
      const taxablePaise = Math.round(quantity * ratePaise);
      await api('/api/documents', json('POST', { document_type: draft.type, party_kind: partyId ? partyKind : null, party_id: partyId || null, sauda_id: draft.sauda_id || null, gate_entry_id: draft.gate_entry_id || null, issue_date: draft.issue_date, gst_rate_pct: Number(draft.gst_rate), tax_mode: draft.tax_mode, lines: [{ item_id: draft.item_id || null, description: draft.description.trim(), quantity, unit: draft.unit, rate_paise: ratePaise, taxable_paise: taxablePaise, gst_rate_pct: Number(draft.gst_rate) }], notes: draft.notes.trim() || null }));
      setDraft(emptyDraft()); await load();
    } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not create document'); } finally { setSaving(false); }
  }
  async function voidDocument(document: Document) { const reason = window.prompt('Void reason (at least 3 characters)'); if (!reason) return; try { setError(null); await api(`/api/documents/${document.id}/void`, json('POST', { reason })); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not void document'); } }
  const filtered = useMemo(() => documents.filter((document) => `${document.document_no ?? ''} ${document.document_type ?? ''} ${document.party_name ?? ''}`.toLowerCase().includes(query.toLowerCase())), [documents, query]);
  const partyOptions = [...(overview?.suppliers ?? []).map(p => ({ ...p, kind: 'supplier' })), ...(overview?.buyers ?? []).map(p => ({ ...p, kind: 'buyer' }))];
  if (session === undefined) return <main className="auth-page"><p className="muted">Loading documents…</p></main>;
  if (!session) return <main className="auth-page"><div className="auth-card"><h1>Sign in required</h1>{sessionError && <p className="error">{sessionError}</p>}<AppLink className="primary" href="/app">Go to login</AppLink></div></main>;
  return <main className="shell"><AppHeader session={session} /><section className="workspace"><div className="dashboard-heading"><div><h2>Documents</h2><p className="muted">Create, upload, print, and void protected business documents.</p></div><AppLink className="primary" href="/app/dashboard">Dashboard</AppLink></div>{error && <p className="error">{error}</p>}
    <section className="panel"><h2>New business document</h2><form className="workflow-form" onSubmit={createDocument}><label>Type<select value={draft.type} onChange={e => setDraft({ ...draft, type: e.target.value })}><option>SALES_INVOICE</option><option>PURCHASE_STATEMENT</option><option>PAYMENT_RECEIPT</option><option>WEIGHMENT_SLIP</option></select></label><label>Party<select value={draft.party} onChange={e => setDraft({ ...draft, party: e.target.value })}><option value="">Not specified</option>{partyOptions.map(p => <option key={`${p.kind}-${p.id}`} value={`${p.kind}:${p.id}`}>{p.name ?? 'Party'} · {p.kind}</option>)}</select></label><label>Item<select value={draft.item_id} onChange={e => setDraft({ ...draft, item_id: e.target.value })}><option value="">Not specified</option>{(overview?.items ?? []).map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Linked Sauda<select value={draft.sauda_id} onChange={e => setDraft({ ...draft, sauda_id: e.target.value })}><option value="">Not specified</option>{(overview?.saudas ?? []).map(sauda => <option key={sauda.id} value={sauda.id}>{sauda.code ?? sauda.id}</option>)}</select></label><label>AppLinked gate<select value={draft.gate_entry_id} onChange={e => setDraft({ ...draft, gate_entry_id: e.target.value })}><option value="">Not specified</option>{(overview?.gate ?? []).map(gate => <option key={gate.id} value={gate.id}>{gate.vehicle_no ?? gate.id}</option>)}</select></label><label>Description<input required value={draft.description} onChange={e => setDraft({ ...draft, description: e.target.value })} /></label><label>Quantity<input required type="number" min="0" step="0.001" value={draft.quantity} onChange={e => setDraft({ ...draft, quantity: e.target.value })} /></label><label>Unit<select value={draft.unit} onChange={e => setDraft({ ...draft, unit: e.target.value })}><option>KG</option><option>QUINTAL</option><option>TONNE</option><option>BAG</option><option>PIECE</option></select></label><label>Rate ₹<input required type="number" min="0" step="0.01" value={draft.rate} onChange={e => setDraft({ ...draft, rate: e.target.value })} /></label><label>GST %<input type="number" min="0" max="100" step="0.01" value={draft.gst_rate} onChange={e => setDraft({ ...draft, gst_rate: e.target.value })} /></label><label>Tax type<select value={draft.tax_mode} onChange={e => setDraft({ ...draft, tax_mode: e.target.value })}><option value="INTRA">CGST + SGST</option><option value="INTER">IGST</option></select></label><label>Issue date<input required type="date" value={draft.issue_date} onChange={e => setDraft({ ...draft, issue_date: e.target.value })} /></label><label>Notes<textarea value={draft.notes} onChange={e => setDraft({ ...draft, notes: e.target.value })} /></label><button className="post" disabled={saving}>{saving ? 'Saving…' : 'Create document'}</button></form></section>
    <section className="panel" style={{ marginTop: 16 }}><h2>Upload document</h2><form className="workflow-form" onSubmit={uploadFile}><label>Type<select value={uploadType} onChange={e => setUploadType(e.target.value)}><option>PAYMENT_RECEIPT</option><option>PURCHASE_STATEMENT</option><option>SALES_INVOICE</option><option>WEIGHMENT_SLIP</option></select></label><label>File (max 1 MB)<input type="file" onChange={e => setUpload(e.target.files?.[0] ?? null)} /></label><button className="post">Upload</button></form></section><input className="stock-search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search document number, type, or party" aria-label="Search documents" /><section className="panel" style={{ marginTop: 16 }}><div className="document-header"><span>Document</span><span>Type</span><span>Party</span><span>Issue date</span><span>Total</span><span>Status</span></div>{filtered.map((document) => <div className="document-row" key={document.id}><strong>{document.document_no ?? '—'}</strong><span>{document.document_type ?? '—'}</span><span>{document.party_name ?? '—'}</span><span>{document.issue_date ?? '—'}</span><strong>{session.role === 'manager' ? 'Restricted' : money(document.total_paise)}</strong><span className="inline-actions"><span className="status">{document.status ?? '—'}</span>{document.upload_name && <a href={`/api/documents/${document.id}/file`} target="_blank">Download</a>}<a href={`/api/documents/${document.id}/print`} target="_blank">Print</a>{document.status === 'POSTED' && <button onClick={() => void voidDocument(document)}>Void</button>}</span></div>)}{!filtered.length && <p className="muted">No matching documents.</p>}</section></section></main>;
}
