'use client';

import { AppLink } from './app-link';
import { FormEvent, useEffect, useMemo, useState } from 'react';
import { AppHeader } from './app-header';
import { useSession } from '../lib/session';
import { api, json } from '../lib/api';

type GateEntry = { id: string; vehicle_no?: string; direction?: 'in' | 'out'; status?: string; item_name?: string; supplier_name?: string; buyer_name?: string; net_kg?: number };
type Reference = { id: string; name: string };
const qtl = (kg?: number) => `${((kg ?? 0) / 100).toLocaleString('en-IN', { maximumFractionDigits: 2 })} qtl`;
const wholeKg = (value: string) => /^\d+$/.test(value) ? Number(value) : null;

export function GateApp() {
  const { session, sessionError } = useSession();
  const [entries, setEntries] = useState<GateEntry[]>([]), [suppliers, setSuppliers] = useState<Reference[]>([]), [buyers, setBuyers] = useState<Reference[]>([]), [items, setItems] = useState<Reference[]>([]);
  const [filter, setFilter] = useState<'all' | 'in' | 'out'>('all'), [error, setError] = useState<string | null>(null), [saving, setSaving] = useState(false);
  const [form, setForm] = useState({ direction: 'in', vehicle_no: '', party_id: '', item_id: '', gross_kg: '', tare_kg: '' });
  const load = async () => { const body = await api<{ gate: GateEntry[]; suppliers: Reference[]; buyers: Reference[]; items: Reference[] }>('/api/overview'); setEntries(body.gate); setSuppliers(body.suppliers); setBuyers(body.buyers); setItems(body.items); };
  useEffect(() => { if (session) void load().catch((cause: unknown) => setError(cause instanceof Error ? cause.message : 'Could not load gate entries')); }, [session]);
  const visible = useMemo(() => entries.filter(e => filter === 'all' || e.direction === filter), [entries, filter]);
  async function submit(event: FormEvent) { event.preventDefault(); const gross = wholeKg(form.gross_kg), tare = wholeKg(form.tare_kg); if (!form.vehicle_no.trim() || !form.party_id || gross == null || tare == null || gross < tare) { setError('Enter a vehicle, party, and whole-kilogram gross and tare weights (gross must be at least tare).'); return; } setSaving(true); setError(null); try { const party = form.direction === 'in' ? { supplier_id: form.party_id } : { buyer_id: form.party_id }; const created = await api<{ id: string }>('/api/gate', json('POST', { direction: form.direction, vehicle_no: form.vehicle_no, item_id: form.item_id || undefined, ...party })); await api(`/api/gate/${created.id}`, json('PATCH', { gross_kg: gross, tare_kg: tare, status: 'weighed' })); setForm({ ...form, vehicle_no: '', party_id: '', item_id: '', gross_kg: '', tare_kg: '' }); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not save gate entry'); } finally { setSaving(false); } }
  async function complete(entry: GateEntry) { const gross = window.prompt('Gross weight in whole kg'); const tare = window.prompt('Tare weight in whole kg'); if (gross == null || tare == null) return; const g = wholeKg(gross), t = wholeKg(tare); if (g == null || t == null || g < t) { setError('Gross and tare must be whole kg, and gross must be at least tare.'); return; } try { await api(`/api/gate/${entry.id}`, json('PATCH', { gross_kg: g, tare_kg: t, status: 'done' })); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not complete gate entry'); } }
  if (session === undefined) return <main className="auth-page"><p className="muted">Loading gate entries…</p></main>;
  if (!session) return <main className="auth-page"><div className="auth-card"><h1>Sign in required</h1>{sessionError && <p className="error">{sessionError}</p>}<AppLink className="primary" href="/app">Go to login</AppLink></div></main>;
  const parties = form.direction === 'in' ? suppliers : buyers;
  return <main className="shell"><AppHeader session={session}/><section className="workspace"><div className="dashboard-heading"><div><h2>Gate & weighbridge</h2><p className="muted">Capture controlled whole-kg weights. Completed weights remain immutable in the Worker.</p></div></div>{error && <p className="error">{error}</p>}<section className="panel"><h2>New gate entry</h2><form className="workflow-form" onSubmit={submit}><label>Direction<select value={form.direction} onChange={e => setForm({ ...form, direction: e.target.value, party_id: '' })}><option value="in">Arriving</option><option value="out">Dispatching</option></select></label><label>Vehicle<input required value={form.vehicle_no} onChange={e => setForm({ ...form, vehicle_no: e.target.value })}/></label><label>Party<select required value={form.party_id} onChange={e => setForm({ ...form, party_id: e.target.value })}><option value="">Select</option>{parties.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Item<select value={form.item_id} onChange={e => setForm({ ...form, item_id: e.target.value })}><option value="">Not specified</option>{items.map(i => <option key={i.id} value={i.id}>{i.name}</option>)}</select></label><label>Gross kg<input required inputMode="numeric" value={form.gross_kg} onChange={e => setForm({ ...form, gross_kg: e.target.value })}/></label><label>Tare kg<input required inputMode="numeric" value={form.tare_kg} onChange={e => setForm({ ...form, tare_kg: e.target.value })}/></label><button className="post" disabled={saving}>{saving ? 'Saving…' : 'Save weighment'}</button></form></section><div className="filter-tabs" role="group" aria-label="Gate direction"><button onClick={() => setFilter('all')} className={filter === 'all' ? 'selected' : ''}>All</button><button onClick={() => setFilter('in')} className={filter === 'in' ? 'selected' : ''}>Arriving</button><button onClick={() => setFilter('out')} className={filter === 'out' ? 'selected' : ''}>Dispatching</button></div><section className="panel" style={{marginTop:16}}><div className="gate-header"><span>Vehicle</span><span>Direction</span><span>Party</span><span>Material</span><span>Net weight</span><span>Status</span></div>{visible.map(entry => <div className="gate-row" key={entry.id}><strong>{entry.vehicle_no ?? '—'}</strong><span>{entry.direction === 'in' ? 'Arriving' : 'Dispatching'}</span><span>{entry.direction === 'in' ? entry.supplier_name ?? '—' : entry.buyer_name ?? '—'}</span><span>{entry.item_name ?? '—'}</span><strong>{qtl(entry.net_kg)}</strong><span className="inline-actions"><span className="status">{entry.status ?? '—'}</span>{entry.status !== 'done' && <button onClick={() => void complete(entry)}>Complete</button>}</span></div>)}</section></section></main>;
}
